#library "Options"
#include "zcommon.acs"

Script "blm_voxmod"(void){
	SetResultValue(GetCVar("blm_voxmod"));	
}

Script "NatureVoxel" (void){
	if(GetCVar("blm_voxcnt")== 0){
		SetResultValue(0);
		SetCvar("r_drawvoxels", 0);
	}else{
		SetCvar("r_drawvoxels", 1);	
		SetResultValue(GetCVar("blm_voxnat"));	
}}

Script "PickupVoxel" (void){
	if(GetCVar("blm_voxcnt")== 0){
		SetCvar("r_drawvoxels", 0);		
		SetResultValue(0);
	}else{
		SetCvar("r_drawvoxels", 1);			
		SetResultValue(GetCVar("blm_voxpkp"));	
}}

Script "LightingVoxel" (void){
	if(GetCVar("blm_voxcnt")== 0){
		SetCvar("r_drawvoxels", 0);			
		SetResultValue(0);
	}else{
		SetCvar("r_drawvoxels", 1);			
		SetResultValue(GetCVar("blm_voxlit"));	
}}

Script "ObjectVoxel" (void){
	if(GetCVar("blm_voxcnt")== 0){
		SetCvar("r_drawvoxels", 0);			
		SetResultValue(0);
	}else{
		SetCvar("r_drawvoxels", 1);			
		SetResultValue(GetCVar("blm_voxobj"));	
}}